# Generated by Django 3.2.8 on 2021-10-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_livro', models.CharField(max_length=30)),
                ('ISBN', models.CharField(max_length=30)),
                ('Titulo_livro', models.CharField(max_length=30)),
                ('autor_livro', models.CharField(max_length=30)),
                ('edicao_livro', models.CharField(max_length=30)),
                ('ano_ancamento', models.CharField(max_length=30)),
                ('cod_biblioteca', models.IntegerField()),
                ('link_livro', models.CharField(max_length=30)),
                ('status_livro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Livros_Id',
            fields=[
                ('livros_id', models.AutoField(primary_key=True, serialize=False)),
                ('livroNome', models.CharField(max_length=30)),
            ],
        ),
    ]
